repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 solution/nordeus_cli
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort solution/nordeus_cli
        language: system
        always_run: true
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black solution/nordeus_cli
        language: system
        always_run: true
        pass_filenames: false
